feat: getAddresses method should expect the account xpub derivation and receive the changeDerivation
HathorNetwork/hathor-wallet-lib pull request #177
Opened 2021-03-23 23:47 UTC by pedroferreira1

2021-03-24 04:05 UTC, msbrogli requested changes
I don't understand what these changes are doing and why they are useful.

2021-03-24 04:05 UTC, msbrogli commented on src/helpers.js
> +    const derivedXpub = xpub.derive(changeDerivation);
I don't get why we need to derive here.

2021-03-24 04:05 UTC, msbrogli commented on src/utils/wallet.ts
> +  getAddresses(xpubkey: string, changeDerivation: number, startIndex: number, quantity: number, networkName: string = 'mainnet'): Object {
I feel I've already seen a similar change in this PR. Why do we need the `changeDerivation` here?

2021-03-25 14:28 UTC, pedroferreira1 commented
This PR is not needed anymore, as discussed privately.

2021-03-25 14:28 UTC, closed without merging