fix: Prevent class defaultOptions from being mutated
HathorNetwork/hathor-wallet-lib pull request #208
Opened 2021-07-01 20:18 UTC by pedroferreira1

2021-07-01 21:41 UTC, andreabadesso requested changes

2021-07-01 21:41 UTC, andreabadesso commented on src/models/output.ts
> +    const { tokenData, timelock } = newOptions;
![](https://media4.giphy.com/media/10uEX5kfeodYgo/giphy.gif)

2021-07-01 21:41 UTC, andreabadesso commented on src/models/input.ts
> +    }
missing `;`

2021-07-01 21:41 UTC, andreabadesso commented on src/models/create_token_transaction.ts
> +    }
missing `;`

2021-07-02 01:53 UTC, andreabadesso approved these changes

2021-07-02 03:42 UTC, msbrogli approved these changes

2021-07-02 15:14 UTC, merged