refactor: move parse script method from output model to an utils method
HathorNetwork/hathor-wallet-lib pull request #605
Opened 2024-01-19 14:15 UTC by pedroferreira1

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2024-01-19 16:32 UTC, andreabadesso requested changes

2024-01-19 16:32 UTC, andreabadesso commented on src/models/output.ts
> +    this.decodedScript = parseScript(this.script, network);
```suggestion
    this.decodedScript = utilsParseScript(this.script, network);
```

2024-01-23 20:21 UTC, alexruzenhack approved these changes

2024-01-23 21:30 UTC, pedroferreira1 commented on src/models/output.ts
> +import { parseScript } from '../utils/scripts'
Done https://github.com/HathorNetwork/hathor-wallet-lib/pull/605/commits/410400a051b6c43e3aae5a3203d925564935ae44

2024-01-23 21:30 UTC, pedroferreira1 commented on src/models/output.ts
> +    this.decodedScript = parseScript(this.script, network);
Done https://github.com/HathorNetwork/hathor-wallet-lib/pull/605/commits/410400a051b6c43e3aae5a3203d925564935ae44

2024-01-24 00:20 UTC, andreabadesso approved these changes

2024-01-24 01:10 UTC, merged