feat: Adds `eslint` for `ts` and `js` files
HathorNetwork/hathor-wallet-lib pull request #669
Opened 2024-06-13 15:57 UTC by tuliomir

### Acceptance Criteria
- Adds `eslint` configuration for all of the project code
- Adds scripts on the `package.json` for easy linting, formatting and error fixing

### Notes
A `.eslintrc` already existed in the repository and was being used to lint the integration test files. The rules on this file were preserved, and it was only moved to a `js` file for improved maintenance convenience.

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2024-06-13 19:04 UTC, andreabadesso requested changes

2024-06-13 19:15 UTC, tuliomir commented on package.json
> +    "eslint-plugin-prettier": "^5.1.3",
Sure! Fixed them.

2024-06-13 19:16 UTC, tuliomir commented on package.json
> +    "@typescript-eslint/parser": "^7.13.0",
Done :+1:

2024-06-13 19:16 UTC, tuliomir commented on package.json
> +    "prettier": "^3.3.2",
Done

2024-06-13 19:17 UTC, tuliomir commented on .eslintrc.js
> +        extensions: ['.js', '.jsx', '.ts', '.tsx'],
That's right. Removed those XML versions on the `import/extensions` rule as well.

2024-06-13 19:17 UTC, tuliomir commented on .eslintrc.js
> +    ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
Updated to the latest available: `2023`.
There's an option to always use the `latest`, but I believe it does not fit with the project's stability requirements, so I fixed it on 2023.

2024-06-13 19:17 UTC, tuliomir commented on .eslintrc.js
> +      files: ['*.ts', '*.tsx'],
Fixed

2024-06-13 19:18 UTC, tuliomir commented on .eslintrc.js
> +        tsx: 'never',
Done

2024-06-17 15:28 UTC, andreabadesso approved these changes

2024-06-17 19:45 UTC, pedroferreira1 approved these changes

2024-06-17 21:25 UTC, merged